name: a3_stringtables_translator
description: Arma 3 stringtable.xml translator.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  googleapis: ^0.56.0
  googleapis_auth: ^0.2.0
  args: ^1.6.0
  xml: ^4.5.1

dev_dependencies:
  pedantic: ^1.9.0
